before_install:
  - "wget https://launchpad.net/ubuntu/+source/cmake/2.8.12.2-0ubuntu3/+build/5826684/+files/cmake_2.8.12.2-0ubuntu3_amd64.deb"
  - "wget https://launchpad.net/ubuntu/+archive/primary/+files/cmake-data_2.8.12.2-0ubuntu3_all.deb"
  - "sudo apt-get remove cmake-data cmake"


install:
  - "sudo dpkg --install cmake-data_2.8.12.2-0ubuntu3_all.deb cmake_2.8.12.2-0ubuntu3_amd64.deb"
  - sudo apt-get install -qq doxygen

language: c

env:
  global:
    - secure: "O+zG6TSo9y2XQOUn8n+LcOIKg40ONpLgdZDYPnGjKM+OYp5dffLUjIWQj7PCknhL7HO+fObLGroLvDI7lWOvD81FhsTl5axGxt8NrtslfAnv6SIBom4dww1acqHTo0C1le1+mdhbB1anm7gYCAdDn3TApWBWbGkAOCkS5JzwqC4="

compiler: 
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake ../ -G"Unix Makefiles" -DCMAKE_C_COMPILER=$(which $CC)
  - make

after_success:
  - #Build the doxygen files and upload to GH pages
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI-DocBuilder"
  - git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/Lectem/libmpo html
  - doxygen Doxyfile
  - cd html
  - git add --all
  - git commit -m"Doc generated from Travis build #$TRAVIS_BUILD_NUMBER"
  - git push -fq origin gh-pages > /dev/null